Redis:
  Host: 'localhost'
  Password: ''
  DbId: 0
BackboneRedis:
  Host: 'localhost'
  Password: ''
  DbId: 0
disableNametags: false
disableDeathmessages: false
NametagPacketRestriction:
  Enabled: false
  BypassPrefix: '&a'